
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgkhvvmbfgsvqowznqpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFna2h2dm1iZmdzdnFvd3pucXBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNTA1MjksImV4cCI6MjA1OTkyNjUyOX0.B1JN_pa-AsaoOwTAezbGo7LgFp-3fVvKDKDjUlpuDEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
